feat: add tailwind to angulars postcss configs
ngneat/tailwind pull request #30
Opened 2020-12-27 17:57 UTC by vltansky

This PR:
- Adds tailwinds [directives & functions](https://tailwindcss.com/docs/functions-and-directives) support (e.g`@apply`).
- Fixes SCSS import issues
- adds LESS & Stylus support
closes #15 #24

As angular >=11.0.5 have PostCSS 8 built-in support and instead of adding a new loader we can (and should) inject tailwind plugin in Angulars PostCSS config. Also as a result that we are adding a tailwind to all Angulars PostCSS configs - any style supported by angular will work with tailwinds `@apply`. You can see it in action here: https://github.com/vltansky/tailwind-ng11
I'm using tailwind in multiple files at the same time: `styles.less`, `app.component.css` and `styles.scss` (sass and stylus should work too)
But I don't have experience with schematics, I didn't succeed to run the `ng add` locally. 
Would be happy to get help with this

2020-12-27 19:31 UTC, nartc commented
Thanks so much for your findings man. I’m happy to help with the PR as soon as I get on my computer.

2020-12-28 02:29 UTC, nartc requested changes

2020-12-28 02:29 UTC, nartc commented on libs/tailwind/src/schematics/files/webpack.config.js.template
> +function patchWebpackPostcssPlugins({
This has way too many options for the schematics to ask the consumers. Are there any options that we can enforce? Like `addPlugins`, this schematics is specific for `tailwindcss` so I don't think we allow `addPlugins` as a parameter at all.

What do` pluginName`, `append`, `atIndex` do? What about `components` and `global`? Can we enforce `global` and `components` to be always true?

2020-12-28 02:29 UTC, nartc commented on libs/tailwind/src/schematics/files/webpack.config.js.template
> +  webpackConfig.module.rules.map((rule) => {
We're mutating `webpackConfig` here so let's use `forEach` instead of `map`. Better yet, use `for...of...` with `continue;` for better readability.

2020-12-28 02:29 UTC, nartc commented on libs/tailwind/src/schematics/files/webpack.config.js.template
> +      const postcssOptions = useLoader.options.postcssOptions;
Let's call this `originPostcssOptions`

2020-12-28 02:29 UTC, nartc commented on libs/tailwind/src/schematics/files/webpack.config.js.template
> +        const pluginIndex =
I need some explanation here. What does `pluginIndex` do? What's this "plugin" in `pluginIndex`?

2020-12-28 02:47 UTC, nartc commented
Without context on some parameters (that I asked in my comments), here's what I came up with for `patchConfig`

```js
function patchConfig(originalConfig, tailwindPlugin) {
  for (let rule of originalConfig.module.rules) {
    if (!(rule.use && rule.use.length)) {
      continue;
    }

    for (let useLoader of rule.use) {
      if (!(useLoader.options && useLoader.options.postcssOptions)) {
        continue;
      }

      const originalPostcssOptions = useLoader.options.postcssOptions;
      useLoader.options.postcssOptions = loader => {
        const _postcssOptions = originalPostcssOptions(loader);
        const autoprefixerIndex = _postcssOptions.plugins
          .findIndex(({postcssPlugin}) => {
            return postcssPlugin && postcssPlugin.toLowerCase() === 'autoprefixer';
          })
        const insertIndex = autoprefixerIndex >= 0
          ? autoprefixerIndex
          : _postcssOptions.plugins.length;
        _postcssOptions.plugins.splice(insertIndex, 0, tailwindPlugin)
        return _postcssOptions
      }
    }
  }
}
```

What do you think?

2020-12-28 04:30 UTC, trungk18 commented
@vltansky Could you please send me a link that mentioned about the below? Because I couldn't see it on Angular documentation. 

> As angular >=11.0.5 have PostCSS 8 built-in support and instead of adding a new loader we can (and should) inject tailwind plugin in Angulars PostCSS config

Btw, great work. I will test it out locally later on.

2020-12-28 06:00 UTC, vltansky commented
@trungk18 according to this commit https://github.com/angular/angular-cli/commit/48c7a85f0ae8ad760c9783ec87f9746741d24828 releases in `11.0.5`

2020-12-28 07:09 UTC, vltansky commented on libs/tailwind/src/schematics/files/webpack.config.js.template
> +      const postcssOptions = useLoader.options.postcssOptions;
done

2020-12-28 07:10 UTC, vltansky commented on libs/tailwind/src/schematics/files/webpack.config.js.template
> +  webpackConfig.module.rules.map((rule) => {
Make sense. Done.

2020-12-28 08:46 UTC, vltansky commented
@nartc as I explained to you in private, the idea was to make a generic function, that potentially could be extracted to stand alone node module. But I'll focus in this PR only on tailwind, so I merged your changes with mine that's what i got:

```js
function patchPostCSS(webpackConfig, tailwindConfig, components = true) {
  const pluginName = "autoprefixer";
  for (const rule of webpackConfig.module.rules) {
    if (!(rule.use && rule.use.length > 0) || (!components && rule.exclude)) {
      continue;
    }
    for (const useLoader of rule.use) {
      if (!(useLoader.options && useLoader.options.postcssOptions)) {
        continue;
      }
      const originPostcssOptions = useLoader.options.postcssOptions;
      useLoader.options.postcssOptions = (loader) => {
        const _postcssOptions = originPostcssOptions(loader);
        const insertIndex = _postcssOptions.plugins.findIndex(
          ({ postcssPlugin }) => postcssPlugin && postcssPlugin.toLowerCase() === pluginName
        );
        if (insertIndex !== -1) {
          _postcssOptions.plugins.splice(insertIndex, 0, ["tailwindcss", tailwindConfig]);
        } else {
          console.error(`${pluginName} not found in postcss plugins`);
        }
        return _postcssOptions;
      };
    }
  }
}

module.exports = (config) => {
  const isProd = config.mode === "production";
  const tailwindConfig = require("./tailwind.config.js")(isProd);
  patchPostCSS(config, tailwindConfig);
  return config;
};


```

Missed anything?

2020-12-28 11:46 UTC, vltansky commented
Actually, it looks like although @angular/cli updated postcss, `@angular-devkit/build-angular` still uses posts 7.
PostCSS 8 will be released in `11.1.x`. 
What I don't understand how tailwind build works for me if it's still postcss 7 under the hood? Is it works for you?

2020-12-28 15:12 UTC, nartc commented
@vltansky That's fair to add `components` to the schematics' options. The code looks good. I just tested it locally and it worked. There are a couple of things left to do on this PR though:
1. Add LESS, Stylus to style option in https://github.com/ngneat/tailwind/blob/master/libs/tailwind/src/schematics/nx-setup/schema.json and https://github.com/ngneat/tailwind/blob/master/libs/tailwind/src/schematics/ng-add/schema.json 
2. Add `enableTailwindInComponentsStyles` to both `schema.json` as well. I'd like to give that a default of `false` instead of `true`. The reason is if the schematics default something to true, it's less likely to make sense to change it otherwise. Let's default it to `false` so that if the consumers want to have their build time affected, they can do so by turning it to `true`
3. Update `schema.d.ts` to reflect the `enableTailwindInComponentsStyles` option
4. Update schematics code so we pass in this `enableTailwindInComponentsStyles` option to `webpack.config.js.template`
5. Update `webpack.config.js.template` to use `enableTailwindInComponentsStyles`.

Also, when you think your PR is ready, please say Yes when `npm run commit` asks if there's any breaking changes. I'd like to release this as a major version bump (aka v4.0.0) instead of minor.

2020-12-28 15:41 UTC, nartc requested changes

2020-12-28 15:41 UTC, nartc commented on libs/tailwind/src/schematics/ng-add/schema.json
> +      "x-prompt": "Would you like to use tailwind directives & functions in component styles?"
nitpick: can we add something to the prompt to let the users know that they might increase build time by turning this on? eg: `...in component styles? (might increase build time)`

2020-12-28 15:41 UTC, nartc commented on libs/tailwind/src/schematics/schema.d.ts
> +  enableTailwindInComponentsStyles: boolean;
thought (non-blocking): Ohhh I now realized that with your change, the schematics should work regardless of what `styles` the users pick for their projects. Please disregard my comment about adding `LESS and STYLUS` to style option.

2020-12-28 15:43 UTC, vltansky commented on libs/tailwind/src/schematics/ng-add/schema.json
> +      "x-prompt": "Would you like to use tailwind directives & functions in component styles?"
done :)

2020-12-28 15:49 UTC, nartc commented
@vltansky Changes look great. Please test it locally and also run `npm run e2e` (e2e might take a while to finish). And just a reminder, did you mark any of the commits breaking changes?

2020-12-28 16:56 UTC, vltansky commented
@nartc I did test it. Worked fine for me.
I marked this one https://github.com/ngneat/tailwind/pull/30/commits/eda8fd52a9bb98c11c2e2d3596770ea18c9c8e1e with breaking change.
e2e passed with some small fixes in tests scripts :)

2020-12-28 17:11 UTC, nartc commented
LGTM. Thanks for the PR

2020-12-28 17:11 UTC, merged