feat: add styles to angular.json or styles file
ngneat/tailwind pull request #31
Opened 2020-12-28 18:41 UTC by vltansky

2021-01-07 02:08 UTC, nartc commented
@vltansky  can we add some test cases for this?

2021-01-07 06:10 UTC, vltansky commented
Changed to `main` branch.
I Will work on tests when I'll have some free time for it.

2021-01-07 13:54 UTC, nartc commented
@vltansky Thanks. The tests for this PR might be a little extensive since you're going to have different app configs. Lemme know if I can help in any way.

2021-01-17 17:30 UTC, vltansky commented
@nartc ready. Take a look.
I think we should disable `npm install` in e2e tests, it takes too long. Styles tests adding another 5 minutes..

2021-01-18 04:09 UTC, nartc commented
@vltansky Yeah, e2e test is nice but we should be testing the content of `angular.json`/`workspace.json` (and the styles files) in various scenarios with unit test.

2021-02-01 15:02 UTC, vltansky commented
@nartc I'd be happy for help here

2021-02-04 20:40 UTC, vltansky commented
Closes #71

2021-02-12 08:20 UTC, vltansky commented
@nartc I've added unit tests. Can you review it?

2021-03-11 16:24 UTC, nartc requested changes

2021-03-11 16:24 UTC, nartc commented on apps/tailwind-e2e/utils/styles.ts
> +  console.log()
question: unuse?

2021-03-11 16:24 UTC, nartc commented on apps/tailwind-e2e/utils/styles.ts
> +    throw `didnt find tailwindcss imports in ${stylesFile}`;
nitpick: let's change the verbiage to "Could not find tailwindcss imports in ${stylesFile}"

2021-03-11 16:24 UTC, nartc commented on apps/tailwind-e2e/utils/styles.ts
> +  removeSync(path.join(localProj, 'webpack.config.js'));
suggestion: probably don't need this with the current code base

2021-03-11 16:24 UTC, nartc commented on libs/tailwind/src/schematics/specs/schematics.spec.ts
> +        throw `didnt find tailwindcss imports in ${stylesFile}`;
nitpick: let's chang to the same verbiage as above

2021-03-11 16:24 UTC, nartc commented on libs/tailwind/src/utils/update-project-root-styles.ts
> +      } else {
nitpick: redundant `else` keyword since we return in the `if` path.

2021-03-11 16:24 UTC, nartc commented on libs/tailwind/src/utils/update-project-root-styles.ts
> +    // }
nitpick: is this comment still needed?

2021-03-11 20:54 UTC, vltansky commented on apps/tailwind-e2e/utils/styles.ts
> +  console.log()
yep. Removed :)

2021-03-11 20:55 UTC, vltansky commented on apps/tailwind-e2e/utils/styles.ts
> +    throw `didnt find tailwindcss imports in ${stylesFile}`;
done

2021-03-11 20:55 UTC, vltansky commented on apps/tailwind-e2e/utils/styles.ts
> +  removeSync(path.join(localProj, 'webpack.config.js'));
We still need the `tailwind.config.js`

2021-03-11 20:56 UTC, vltansky commented on libs/tailwind/src/schematics/specs/schematics.spec.ts
> +        throw `didnt find tailwindcss imports in ${stylesFile}`;
done

2021-03-11 20:56 UTC, vltansky commented on libs/tailwind/src/utils/update-project-root-styles.ts
> +    // }
removed

2021-03-11 20:57 UTC, vltansky commented on libs/tailwind/src/utils/update-project-root-styles.ts
> +      } else {
done

2021-03-11 21:18 UTC, nartc commented on apps/tailwind-e2e/utils/styles.ts
> +  removeSync(path.join(localProj, 'webpack.config.js'));
I'm talking about the webpack

2021-03-12 06:43 UTC, vltansky commented on apps/tailwind-e2e/utils/styles.ts
> +  removeSync(path.join(localProj, 'webpack.config.js'));
Then it's done;)

2021-03-13 02:29 UTC, nartc approved these changes

2021-03-13 02:29 UTC, merged