docs: add installing tailwindcss to manual steps
ngneat/tailwind pull request #69
Opened 2021-02-02 08:52 UTC by vltansky

@nartc maybe you will want to write it another way. But schematics adds tailwindcss, so manual steps should include it too.
Also there is no need to add postcss anymore.

2021-02-04 03:42 UTC, nartc commented
Apparently, Nx still generates a new Angular app with 11.0.7 instead of 11.1 so no PostCSSv8 unfortunately. Let's add this to the README in this PR as well

- Nx Workspace users still need to install `postcss` as a devDependencies manually regardless of `Manual Steps` or not

Also, can you update the README inside of `libs/tailwind` as well. Thanks

2021-02-04 03:42 UTC, nartc requested changes
Apparently, Nx still generates a new Angular app with 11.0.7 instead of 11.1 so no PostCSSv8 unfortunately. Let's add this to the README in this PR as well

- Nx Workspace users still need to install `postcss` as a devDependencies manually regardless of `Manual Steps` or not

Also, can you update the README inside of `libs/tailwind` as well. Thanks

2021-02-07 07:37 UTC, vltansky commented
@nartc maybe we should return installing postcss? anyway npm 7 installing peer dependencies automatically.
Yarn is showing warnings when peer dependency not installed, Nx generates angular 11.0.7, ionic generation angular 10. So many things will be fixed by just adding one dependency :)

2021-03-13 02:31 UTC, nartc approved these changes

2021-03-13 02:31 UTC, merged