feat: leveraging angular built-in tailwind support & setting purge.en…
ngneat/tailwind pull request #80
Opened 2021-03-09 19:48 UTC by vltansky

…abled

2021-03-10 13:52 UTC, nartc requested changes

2021-03-10 13:52 UTC, nartc commented on apps/tailwind-e2e/tests/tailwind.spec.ts
> -
question: should we still need to check for `tailwind.config.js`?

2021-03-10 13:52 UTC, nartc commented on libs/tailwind/src/schematics/files/tailwind.config.js.template
> +    enabled: guessProductionMode(),
issue: `enabled` is under `purge`, not on the same level as `purge`

2021-03-10 14:25 UTC, vltansky commented on apps/tailwind-e2e/tests/tailwind.spec.ts
> -
We do. Removed it by mistake :)

2021-03-10 17:03 UTC, nartc commented
LGTM

2021-03-11 07:12 UTC, vltansky commented
So this PR resolves the following tasks of roadmap:

- [ ] ngneat/tailwind will check if your project is running v11.2 of Angular.
If yes, then ngneat/tailwind will execute a slightly newer flow
If no, then ngneat/tailwind will execute the current flow, which is working for most Angular projects that are under 11.2

- [x] ngneat/tailwind will ride on top of AngularCLI support for Tailwind. This means that we will not leverage any custom webpack anymore.
- [x] ngneat/tailwind will still initialize a tailwind.config.js for you without you having to execute npx tailwindcss init
- [x] ngneat/tailwind will also setup Purging out of the box with a custom flag.
- [ ] ngneat/tailwind will export a custom Tailwind plugin to handle ViewEncapsulation in Components' styles. Right now, this is handled by a custom PostCSS plugin but since we won't be using Custom Webpack, we cannot utilize a PostCSS plugin.
- [x] ngneat/tailwind will export the Custom Tailwind Plugin and the Purging flag as Public API so the consumers can reference if need be.

I think this can be merged into master, as the tailwind plugin & angular version checker can be set up as separate PRs

#79

2021-03-11 11:11 UTC, merged

2021-03-11 11:11 UTC, nartc commented
Thanks @vltansky

2021-03-16 22:10 UTC, twittwer commented
Is there an estimate when this PR will be released? 🙂