feat: update to Nx11
ngneat/tailwind pull request #87
Opened 2021-04-05 03:02 UTC by nartc

This PR proposes the following changes:
- updates the repo to Nx 11, AngularCLI 11, and Angular Schematics v11
- adds `checkCliVersion` to check for AngularCLI 11.2
- skips unit tests as there are bugs in the Nrwl schematics itself.
- skips e2e tests as the `nrwl/angular` schematics installs Angular v11.0.7 and will not pass Angular CLI version check

The tests are skipped but the schematics have been verified locally.

2021-04-05 07:32 UTC, vltansky approved these changes

2021-04-05 07:32 UTC, vltansky commented on .husky/pre-commit
> +npx lint-staged
Would we maybe want to use [simple-git-hooks](https://github.com/toplenboren/simple-git-hooks) instead of husky?

2021-04-05 08:07 UTC, vltansky requested changes
```
$ npm run build

> @ngneat/tailwind@6.0.3 build D:\projects\tailwind
> ng run tailwind:build-copy


>  NX   ERROR  Cannot find target 'build-copy' for project 'tailwind'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ngneat/tailwind@6.0.3 build: `ng run tailwind:build-copy`
npm ERR! Exit status 1
```

changing to `nx run tailwind:build-copy` fixes it for me

2021-04-05 08:21 UTC, vltansky commented
```
$ npm run test

> tailwind-test@0.0.0 test D:\projects\tailwind-test
> npx ng generate ./../tailwind/dist/libs/tailwind:ng-add

? Would you like to enable dark mode? none
? What @tailwindcss plugins do you want to enable?

    Detected AngularCLI version is 11.1.4 which does not support TailwindCSS natively.
    Please run "ng add @ngneat/tailwind@6" for Custom Webpack support.

Nothing to be done.
```

Version check works :)

2021-04-07 03:54 UTC, nartc commented on .husky/pre-commit
> +npx lint-staged
Will do!

2021-04-07 03:58 UTC, merged